### ISSUE TITLE
Multiple Prompts showed

### ISSUE THREAD

**Issue by amoeba-grade-0w** [lithnet/access-manager#235] opened 2024-08-12 02:43 UTC
Multiple prompts showed when using User Prompts in RapidLAPS. 
When user prompt deactivated, the user prompt still exist and when re-activated, i.e from text to dropdown list, both prompts showed.
![IMG_9066](https://github.com/user-attachments/assets/a6cb5155-b3e8-4abf-bc9d-ebd924c8baa8)

**Comment by ryannewington** [comment] 2024-08-12 04:28
@amoeba-grade-0w thanks for reaching out with this one.

What are the steps you need to take to reproduce this issue?

**Comment by amoeba-grade-0w** [comment] 2024-08-12 04:56
Hi Ryan, thanks for the response.

this happens all the time since I’m using version 3. I was using version 2 (community edition) and upgraded to version 3 to test the rapidlaps.
since upgraded and installed the agent on client ( tested on windows 10, windows 11 and windows 2016), the clients always shows multiple prompts (like the screenshot above).
never get the QR, since I cant continue to the next step.

**Comment by ryannewington** [comment] 2024-08-12 05:45
When you open the policy on the server side, do the duplicates appear there?

**Comment by amoeba-grade-0w** [comment] 2024-08-12 06:28
no duplicates on the server side.
even I removed the User Prompt, the prompt still appear in the client
![IMG_9071](https://github.com/user-attachments/assets/34f59971-61bf-4833-a90a-d22d545a8754)

**Comment by ryannewington** [comment] 2024-08-12 06:55
Ok thanks so much for the info. We'll continue the investigation on our side.

The agents only check in for policy updates once per hour, so the prompts should be removed once that happens.

**Comment by amoeba-grade-0w** [comment] 2024-08-12 09:36
Thank You.
For your information, its been hours since I removed the user prompts on the console and its still appears in the client. also tried to re-install the agent and rebooted the client, still the same.

**Comment by astular** [comment] 2024-08-13 07:46
![LithnetPolicies](https://github.com/user-attachments/assets/0fb93fc4-0458-4414-bd9d-f607c22940cc)
![20240813_094340](https://github.com/user-attachments/assets/695f9ee9-906d-445b-8156-d4232a4b8831)
I have exactly the same issue. Upgraded yesterday to v3, installed a single AMS agent to test RapidLAPS. Initially I have modified the default windows agent policy because I am unable to add a custom policy (the Create new button is grayed out). In the default policy I configured a simple user prompt, which was then shown multiple times on the client. If I enter some text on all of the fields I am able to continue, but the code is not shown. On the server there are two errors in the logs with event ID 0 and 1 with this text: 
RequestPath: /api/v3.0/agent/devicelogin/request
A licensing error occurred
Exception: 
Lithnet.Licensing.Core.NoLicensePresentException: There is no valid license on the system

One more note: I have since removed the user prompt from the default policy, but the multiple user prompts are still shown on the client.

**Comment by ryannewington** [comment] 2024-08-16 19:05
Hi guys, we're able to reproduce this one in the lab, and have a fix incoming.

As a workaround, you can restart the AMS service after each config change to clear the duplicate entries. They will double on each save, due to a caching issue.

**Comment by ryannewington** [comment] 2024-08-17 13:34
Hi guys, 

This has been resolved in 3.0.1217 available here https://packages.lithnet.io/win/access-manager-service/v3.0/x64/latest

**Comment by astular** [comment] 2024-08-19 12:23
Hi! I can confirm that the problem has been resolved. However I have another issue with using RapidLAPS, but I will post that in another thread. Thank you for your quick response! RapidLAPS is really a great addition to Lithnet Access Manager. Keep up the good work!

**Comment by amoeba-grade-0w** [comment] 2024-08-20 02:28
Hi, can confirm the latest version work.

thank you for the support

**Closed as completed** 2024-08-20 04:44 UTC
