### ISSUE TITLE
Add support for http proxy with authentication

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#25] opened 2020-09-08 07:43 UTC
Hello,
I receive a lot of errors like:

Category: Lithnet.AccessManager.Server.UI.HostingViewModel
EventId: 8006

Could not get version update

Exception: 
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Lithnet.AccessManager.Server.UI.HostingViewModel.DownloadFile(String url) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server.UI\ViewModels\HostingViewModel.cs:line 745
   at Lithnet.AccessManager.Server.UI.HostingViewModel.TryGetVersion() in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server.UI\ViewModels\HostingViewModel.cs:line 711

According to my understanding, AMS is trying to verify is there is an update in an on-line repository.
In Enterprise environment, usually servers are not authorized to connect to Internet so it would be fine to have
a new configuration main page with:

- Enable/Disable Check for Upgrades
- Download/notify for Updates
- Define proxy setting supporting Authentication to connect to the Internet

Regards,

Red.

**Comment by ryannewington** [comment] 2020-09-08 21:24
Do you have a proxy, and the problem is that AMS not finding/using it, or do you have no internet access at all on this host?

Control over updates and notifications is planned for a future version. At the moment, it's just a simple API check to see if a new version is available.

________________________________

**Comment by red-erik** [comment] 2020-09-09 06:15
Hello,
we use a proxy with Authentication but servers are completely disconnected from Internet.

**Comment by ryannewington** [comment] 2020-09-11 23:03
Added support for detecting the default proxy and using the user's default credentials.

**Comment by ryannewington** [comment] 2020-09-12 05:34
This fix is included in [beta-2](https://github.com/lithnet/access-manager/releases/tag/v1.0.7608-beta.2). Please reopen this ticket if there are any issues.

**Closed by ryannewington** 2020-09-12 05:34 UTC
Labels: enhancement, pinned
