### ISSUE TITLE
Add support for looking up computers by dnsHostName attribute

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#3] opened 2020-08-18 13:33 UTC
I am not sure if this is yet implemented in AccessManager, but in LAPS WEB when fqdn computer name was given the error:  The requested computer was not found in the directory shows up. 

![image](https://user-images.githubusercontent.com/15063294/90519114-e9e1ec80-e167-11ea-9bb6-aa7f705009ee.png)

**Comment by ryannewington** [comment] 2020-08-18 21:46
Added support for looking up via the dnsHostName attribute in AD. This will be the primary machine dns entry. I'm not going to try and to lookups for dns alternate names.

Can we start a new discussion for the other issue around failure events. I think that warrants discussion on its own

**Comment by ryannewington** [comment] 2020-08-18 22:07
Hmm, looks like this method can't be used across forest trusts, we have to use the global catalog for this lookup, as we can't call the usual trust-aware APIs as they don't have support for dns name translation.

I'm wondering if it's best in this case to leave this functionality out for now? I don't want to have a bunch of inconsistencies in behavior based on AD topology that the user might not be aware of.

**Comment by PrzemyslawKlys** [comment] 2020-08-18 22:09
I think that everything can wait. I mean you take your time as much as you need it. I'm opening it up because I believe it's good to have some kind of roadmap or information that may be interesting for people. Don't feel obligated to deliver it on day one or even day 500.

**Comment by PrzemyslawKlys** [comment] 2020-08-18 22:17
This seems to work
```powershell
Get-ADComputer -Server ADTest.test.evotec.pl:3268 -Filter { DnshostName -eq 'ADTest.test.evotec.pl' -or Name -eq 'adtest' }
Get-ADComputer -Server ADTest.test.evotec.pl:3268 -Filter { DnshostName -eq 'ADTest.test.evotec.pl' }
```

Or are you thinking about something else? 

Or maybe something like this:

```
Get-ADObject -LDAPFilter { (&(ObjectClass=Computer)(ANR=ADTest) ) } -Server ADTest.test.evotec.pl:3268 -Properties *
```

**Comment by ryannewington** [comment] 2020-08-19 09:58
If its within the same forest, it works fine as we are using the GC. 

The problem is the lookup against the local GC fails when the computer is in another forest. I'm not too keen on enumerating all the trusts and searching them one-by-one for a match as that's fairly expensive.

**Comment by ryannewington** [comment] 2020-09-20 00:35
Adds support for this. First we search the GC in the local forest for a match on the dnsHostname attribute.

If none is found, then we separate the host from the domain component in the name provided, and try and convert the dns domain name to an NT4 domain name. If we are able to do that, then we can build an NT4-style computer name, which we can submit to DsCrackNames which will find the computer in whatever forest it resides in.

This will be in beta 3

**Comment by PrzemyslawKlys** [comment] 2020-09-20 09:11
I do it using LDAP query without checking for anything special

![image](https://user-images.githubusercontent.com/15063294/93707733-71d56080-fb31-11ea-82e4-b5f90d9423b6.png)

![image](https://user-images.githubusercontent.com/15063294/93707713-494d6680-fb31-11ea-9b99-7de393a4cb77.png)

As long as you have logic to distinguish whether it's DN, ComputerName, or ComputerName with the full name you should be able to query LDAP with the following filter

$Search.filter = "(|(DistinguishedName=$Ident)(Name=$Ident)(SamAccountName=$Ident)(UserPrincipalName=$Ident)(objectGUID=$IdentityGUID)(objectSid=$Ident))"

You just need to supply domain where the object resides but getting it from DN/FullName isn't hard. 

https://github.com/EvotecIT/ADEssentials/blob/357295f5c939c0bd8d0934e7c2548a96415a5c1d/Public/Get-WinADObject.ps1#L104-L126

And then 

https://github.com/EvotecIT/ADEssentials/blob/357295f5c939c0bd8d0934e7c2548a96415a5c1d/Public/Get-WinADObject.ps1#L148-L183

**Comment by ryannewington** [comment] 2020-09-20 09:30
I don't use LDAP searches to find computers because it doesn't work with multi forest environments. I use DsCrackNames to convert the various name types to DN and then get the full object from the authoritative LDAP server in the appropriate forest. DsCrackNames doesn't support dns names.

Anyway, it's all working. I've added support for this and it will be in the next release.

**Comment by PrzemyslawKlys** [comment] 2020-09-20 10:57
What you mean it doesnt support multiforest? If there is a trust it supports multiforest. On the screenshot above test.evotec.pl is one forest, and ad.evotec.xyz is another forest with additional domain ad.evotec.pl. Unless you mean 2 separate forests without trusts...

**Comment by ryannewington** [comment] 2020-09-20 11:43
If I do a global catalog search in myforest.local for (dnsHostName=computer.otherforest.local) I don't get any results

**Comment by PrzemyslawKlys** [comment] 2020-09-20 13:32
Right. I don't query GC. 

I simply take a value and if it contains dots split it on the first dot. Since computer names are not allowed to have dots you're pretty safe there that everything after first dot will be domain name. 

```
function Test-Me {
    param(
        [string] $Ident
    )
    $Search = $Null
    if ($Ident -like '*.*') {
        # Extract DomainName from name
        $CNConversion = $Ident -split '\.', 2
        $Ident = $CNConversion[0]
        $TemporaryDomainName = $CNConversion[1]
    } elseif ($Ident -like "*DC=*") {
        # Extract DomainName from DN
        $DN = $Ident -replace '.*?((DC=[^=]+,)+DC=[^=]+)$', '$1'
        $CN = $DN -replace ',DC=', '.' -replace "DC="
        $TemporaryDomainName = $CN
    }

    $Search = [System.DirectoryServices.DirectorySearcher]::new()
    $Search.filter = "(|(DistinguishedName=$Ident)(Name=$Ident)(SamAccountName=$Ident)(UserPrincipalName=$Ident)(objectSid=$Ident))"
    if ($TemporaryDomainName) {
        $Search.SearchRoot = "LDAP://$TemporaryDomainName"
    }
    $Result = $Search.FindAll()
    $Result
}
$Idents = @(
    'test8.test.evotec.pl' # another forest
    'EVOWIN' # current domain
    'CN=test8,CN=Computers,DC=test,DC=evotec,DC=pl' # another forest
)

$Output = foreach ($Ident in $Idents) {
    Test-Me $Ident
}
$Output | Format-Table
```

This makes sure the search works across forests.

**Comment by ryannewington** [comment] 2020-10-03 23:38
This feature is now in beta-3

https://github.com/lithnet/access-manager/releases/tag/v1.0.7624.0-beta.3

**Closed by ryannewington** 2020-10-03 23:38 UTC
Labels: enhancement, pinned
